vulnerabilities:
  - id: CVE-2025-61726
    statement: wait for goreleaser v2.14.0
    expired_at: 2026-03-01
  - id: CVE-2025-61728
    statement: wait for goreleaser v2.14.0
    expired_at: 2026-03-01
